name: spotify_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  extended_image: ^6.3.4
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.0
  flutter_screenutil: ^5.6.0
  go_router: ^6.0.0
  heroicons: ^0.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/main-icon.png
    - assets/icons/white-icon.png
    - assets/icons/google.png
    - assets/icons/facebook.png
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamBook.ttf
          weight: 600
        - asset: assets/fonts/GothamBold.ttf
          weight: 800
        - asset: assets/fonts/GothamLight.ttf
          weight: 200
        - asset: assets/fonts/GothamMedium.ttf
          weight: 400
